# NOT IN USE
# trying to get Server registered in pgadmin automatically - haven't succeeded yet

FROM dpage/pgadmin4

COPY servers.json /pgadmin/servers.json
COPY pgpass /pgadmin/pgadmin
# COPY sql/ /var/lib/pgadmin/storage/admin_example.com/