name: Run Prettier and ESLint
on:
  push:
  pull_request:
    branches:
        - main
    paths:
        - '**.ts'
        - '**.vue'
jobs:
  prettify:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Install packages
        run: npm ci

      - name: Run Prettier
        run: npm run format

      - name: Lint
        run: npm run lint
